[project]
name = "uv-global-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samuel Oliveira", email = "renard162@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "shellingham~=1.5.4",
]

[project.scripts]
uve = "uv_global_manager.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
