[project]
name = "uv-global-manager"
version = "1.0.1"
description = "A cross-platform, multi-shell CLI for managing reusable global Python environments with uv and bootstrapping standard uv projects."
readme = "README.md"

authors = [
    { name = "Samuel Oliveira" },
]

license = "MIT"
license-files = ["LICENSE"]

keywords = [
    "uv",
    "python",
    "virtual-environment",
    "global-environment",
    "environment-manager",
    "cli",
    "shell",
    "cross-platform",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Shells",
]

requires-python = ">=3.10"

dependencies = [
    "shellingham==1.5.4",
]


[project.urls]
Homepage = "https://pypi.org/project/uv-global-manager"
Repository = "https://github.com/renard162/uv-global-manager"
Issues = "https://github.com/renard162/uv-global-manager/issues"


[project.scripts]
uve = "uv_global_manager.main:main"


[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
